### ISSUE TITLE
Update to python3

### ISSUE THREAD

**Issue by tkrauthoff** [sandeepsajan0/Snake-game#7]
Update the code to python3 because python2 is somehow deprecated.

**Comment by AlbertosaurusrexDK** [comment]
> i might be able to take a look at that when i get home

I've taken a quick look now, it should work but i haven't tested it.

**Comment by IgorOliveira42** [comment]
Can I look?

**Comment by sandeepsajan0** [comment]
@tkrauthoff is already working on it.

**Comment by tkrauthoff** [comment]
Already fixed in https://github.com/sandeepsajan0/Snake-game/pull/8

**Comment by sandeepsajan0** [comment]
Thanks, @tkrauthoff
